<a href="https://colab.research.google.com/github/AkshayKulkarni1904/Python/blob/main/practice/day_24_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
path='/content/CO2 Emissions_Canada.csv'

In [2]:
import pandas as pd
c=pd.read_csv(path)

In [3]:
c['Make'].unique()

array(['ACURA', 'ALFA ROMEO', 'ASTON MARTIN', 'AUDI', 'BENTLEY', 'BMW',
       'BUICK', 'CADILLAC', 'CHEVROLET', 'CHRYSLER', 'DODGE', 'FIAT',
       'FORD', 'GMC', 'HONDA', 'HYUNDAI', 'INFINITI', 'JAGUAR', 'JEEP',
       'KIA', 'LAMBORGHINI', 'LAND ROVER', 'LEXUS', 'LINCOLN', 'MASERATI',
       'MAZDA', 'MERCEDES-BENZ', 'MINI', 'MITSUBISHI', 'NISSAN',
       'PORSCHE', 'RAM', 'ROLLS-ROYCE', 'SCION', 'SMART', 'SRT', 'SUBARU',
       'TOYOTA', 'VOLKSWAGEN', 'VOLVO', 'GENESIS', 'BUGATTI'],
      dtype=object)

In [12]:
c.columns

Index(['Make', 'Model', 'Vehicle Class', 'Engine Size(L)', 'Cylinders',
       'Transmission', 'Fuel Type', 'Fuel Consumption City (L/100 km)',
       'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)',
       'Fuel Consumption Comb (mpg)', 'CO2 Emissions(g/km)'],
      dtype='object')

In [13]:
#Display all unique fuel types
c["Fuel Type"].unique()

array(['Z', 'D', 'X', 'E', 'N'], dtype=object)

In [16]:
#Find the average CO2 emission of all vehicles
print(c['CO2 Emissions(g/km)'].mean())

250.58469871360867

In [18]:
#For rounded output:
print(round(c['CO2 Emissions(g/km)'].mean(),2))

250.58

In [19]:
#Find the vehicle with the highest CO2 emission
c.loc[c['CO2 Emissions(g/km)'].max()]

Make                                 HYUNDAI
Model                               VELOSTER
Vehicle Class                        COMPACT
Engine Size(L)                           1.6
Cylinders                                  4
Transmission                             AM6
Fuel Type                                  X
Fuel Consumption City (L/100 km)         8.6
Fuel Consumption Hwy (L/100 km)          6.6
Fuel Consumption Comb (L/100 km)         7.7
Fuel Consumption Comb (mpg)               37
CO2 Emissions(g/km)                      177
Name: 522, dtype: object

In [20]:
#Find the vehicle with the lowest CO2 emission
c.loc[c['CO2 Emissions(g/km)'].min()]

Make                                              BMW
Model                               435i xDRIVE COUPE
Vehicle Class                                 COMPACT
Engine Size(L)                                    3.0
Cylinders                                           6
Transmission                                       A8
Fuel Type                                           Z
Fuel Consumption City (L/100 km)                 11.7
Fuel Consumption Hwy (L/100 km)                   7.8
Fuel Consumption Comb (L/100 km)                  9.9
Fuel Consumption Comb (mpg)                        29
CO2 Emissions(g/km)                               228
Name: 96, dtype: object

In [22]:
#Find all vehicles having engine size greater than 4 litres
c.query("`Engine Size(L)`>4")

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
13,ASTON MARTIN,DB9,MINICOMPACT,5.9,12,A6,Z,18.0,12.6,15.6,18,359
14,ASTON MARTIN,RAPIDE,SUBCOMPACT,5.9,12,A6,Z,18.0,12.6,15.6,18,359
15,ASTON MARTIN,V8 VANTAGE,TWO-SEATER,4.7,8,AM7,Z,17.4,11.3,14.7,19,338
16,ASTON MARTIN,V8 VANTAGE,TWO-SEATER,4.7,8,M6,Z,18.1,12.2,15.4,18,354
17,ASTON MARTIN,V8 VANTAGE S,TWO-SEATER,4.7,8,AM7,Z,17.4,11.3,14.7,19,338
...,...,...,...,...,...,...,...,...,...,...,...,...
7291,ROLLS-ROYCE,Phantom EWB,FULL-SIZE,6.7,12,AS8,Z,20.0,11.8,16.3,17,382
7292,ROLLS-ROYCE,Wraith,MID-SIZE,6.6,12,AS8,Z,19.6,12.8,16.5,17,387
7348,TOYOTA,Sequoia 4WD,SUV - STANDARD,5.7,8,AS6,X,18.5,13.9,16.4,17,385
7356,TOYOTA,Tundra,PICKUP TRUCK - STANDARD,5.7,8,AS6,X,17.7,13.6,15.9,18,371
7357,TOYOTA,Tundra 4WD,PICKUP TRUCK - STANDARD,5.7,8,AS6,X,18.0,14.2,16.3,17,381

In [26]:
#find the total number:
len(c[c["Engine Size(L)"] > 4])

1495

In [29]:
#Count the number of vehicles for each manufacturer
c['Make'].value_counts()

Make
FORD             628
CHEVROLET        588
BMW              527
MERCEDES-BENZ    419
PORSCHE          376
TOYOTA           330
GMC              328
AUDI             286
NISSAN           259
JEEP             251
DODGE            246
KIA              231
HONDA            214
HYUNDAI          210
MINI             204
VOLKSWAGEN       197
MAZDA            180
LEXUS            178
JAGUAR           160
CADILLAC         158
SUBARU           140
VOLVO            124
INFINITI         108
BUICK            103
RAM               97
LINCOLN           96
MITSUBISHI        95
CHRYSLER          88
LAND ROVER        85
FIAT              73
ACURA             72
MASERATI          61
ROLLS-ROYCE       50
ASTON MARTIN      47
BENTLEY           46
LAMBORGHINI       41
ALFA ROMEO        30
GENESIS           25
SCION             22
SMART              7
BUGATTI            3
SRT                2
Name: count, dtype: int64

In [32]:
#Find the average CO2 emission for each fuel type
c.groupby("Fuel Type")["CO2 Emissions(g/km)"].mean()

Fuel Type
D    237.548571
E    275.091892
N    213.000000
X    235.119329
Z    266.043410
Name: CO2 Emissions(g/km), dtype: float64

In [33]:
#Find the top 5 manufacturers with the highest average CO2 emission
c.groupby('Make')['CO2 Emissions(g/km)'].mean().sort_values(ascending=False).head()

Make
BUGATTI        522.000000
LAMBORGHINI    400.780488
SRT            389.000000
ROLLS-ROYCE    388.480000
BENTLEY        362.934783
Name: CO2 Emissions(g/km), dtype: float64

In [34]:
#Find all BMW vehicles with CO2 emissions greater than 300 g/km
c[(c['Make']=='BMW')&(c['CO2 Emissions(g/km)']>300)]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
112,BMW,760Li,FULL-SIZE,6.0,12,A8,Z,18.7,11.5,15.5,18,356
118,BMW,M5,MID-SIZE,4.4,8,AM7,Z,17.3,11.5,14.7,19,338
119,BMW,M5,MID-SIZE,4.4,8,M6,Z,16.2,10.9,13.8,20,317
120,BMW,M6,COMPACT,4.4,8,AM7,Z,17.3,11.5,14.7,19,338
121,BMW,M6,COMPACT,4.4,8,M6,Z,16.2,10.9,13.8,20,317
...,...,...,...,...,...,...,...,...,...,...,...,...
6631,BMW,X5 xDrive50i,SUV - STANDARD,4.4,8,AS8,Z,14.5,10.7,12.8,22,302
6632,BMW,X5 M50i,SUV - STANDARD,4.4,8,AS8,Z,14.5,10.7,12.8,22,302
6634,BMW,X6 M50i,SUV - STANDARD,4.4,8,AS8,Z,14.5,10.7,12.8,22,302
6636,BMW,X7 xDrive50i,SUV - STANDARD,4.4,8,AS8,Z,15.5,11.4,13.6,21,318
6637,BMW,X7 M50i,SUV - STANDARD,4.4,8,AS8,Z,15.5,11.4,13.6,21,318

In [35]:
#Sort the dataset based on CO2 emissions from highest to lowest
c.sort_values(by='CO2 Emissions(g/km)',ascending=False)

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
6640,BUGATTI,Chiron,TWO-SEATER,8.0,16,AM7,Z,26.8,16.6,22.2,13,522
5575,BUGATTI,Chiron,TWO-SEATER,8.0,16,AM7,Z,26.8,16.6,22.2,13,522
4509,BUGATTI,CHIRON,TWO-SEATER,8.0,16,AM7,Z,26.8,16.6,22.2,13,522
7059,LAMBORGHINI,Aventador Roadster,TWO-SEATER,6.5,12,AM7,Z,26.6,15.8,21.7,13,493
6046,LAMBORGHINI,Aventador Roadster,TWO-SEATER,6.5,12,AM7,Z,26.6,15.8,21.7,13,493
...,...,...,...,...,...,...,...,...,...,...,...,...
6949,HYUNDAI,IONIQ,FULL-SIZE,1.6,4,AM6,X,4.2,4.2,4.2,67,99
6950,HYUNDAI,IONIQ Blue,FULL-SIZE,1.6,4,AM6,X,4.2,4.0,4.1,69,96
5931,HYUNDAI,IONIQ Blue,FULL-SIZE,1.6,4,AM6,X,4.2,4.0,4.1,69,96
4900,HYUNDAI,IONIQ BLUE,FULL-SIZE,1.6,4,AM6,X,4.2,4.0,4.1,69,96
3824,HYUNDAI,IONIQ BLUE,FULL-SIZE,1.6,4,AM6,X,4.2,4.0,4.1,69,96

In [36]:
#top 10
c.sort_values(by='CO2 Emissions(g/km)',ascending=False).head(10)

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
6640,BUGATTI,Chiron,TWO-SEATER,8.0,16,AM7,Z,26.8,16.6,22.2,13,522
5575,BUGATTI,Chiron,TWO-SEATER,8.0,16,AM7,Z,26.8,16.6,22.2,13,522
4509,BUGATTI,CHIRON,TWO-SEATER,8.0,16,AM7,Z,26.8,16.6,22.2,13,522
7059,LAMBORGHINI,Aventador Roadster,TWO-SEATER,6.5,12,AM7,Z,26.6,15.8,21.7,13,493
6046,LAMBORGHINI,Aventador Roadster,TWO-SEATER,6.5,12,AM7,Z,26.6,15.8,21.7,13,493
349,FORD,E350 WAGON,VAN - PASSENGER,6.8,10,A5,X,23.9,17.8,21.2,13,488
6045,LAMBORGHINI,Aventador Coupe,TWO-SEATER,6.5,12,AM7,Z,26.3,15.6,21.5,13,487
7058,LAMBORGHINI,Aventador Coupe,TWO-SEATER,6.5,12,AM7,Z,26.2,15.5,21.4,13,485
2971,MERCEDES-BENZ,AMG G 65,SUV - STANDARD,6.0,12,AS7,Z,24.3,17.9,21.4,13,476
5126,MERCEDES-BENZ,AMG G 65,SUV - STANDARD,6.0,12,A7,Z,22.2,18.0,20.3,14,473

In [37]:
#Find the correlation between engine size and CO2 emissions
c['Engine Size(L)'].corr(c['CO2 Emissions(g/km)'])

np.float64(0.8511446437900007)

In [47]:
#Create a second dataset
manufacturer_data = {
    "Make": [
        "ACURA",
        "AUDI",
        "BMW",
        "CHEVROLET",
        "FORD",
        "HONDA",
        "HYUNDAI",
        "MERCEDES-BENZ",
        "TOYOTA",
        "VOLKSWAGEN"
    ],

    "Country": [
        "Japan",
        "Germany",
        "Germany",
        "USA",
        "USA",
        "Japan",
        "South Korea",
        "Germany",
        "Japan",
        "Germany"
    ],

    "Company_Type": [
        "Luxury",
        "Luxury",
        "Luxury",
        "Mass Market",
        "Mass Market",
        "Mass Market",
        "Mass Market",
        "Luxury",
        "Mass Market",
        "Mass Market"
    ]
}

c2 = pd.DataFrame(manufacturer_data)

c2

            Make      Country Company_Type
0          ACURA        Japan       Luxury
1           AUDI      Germany       Luxury
2            BMW      Germany       Luxury
3      CHEVROLET          USA  Mass Market
4           FORD          USA  Mass Market
5          HONDA        Japan  Mass Market
6        HYUNDAI  South Korea  Mass Market
7  MERCEDES-BENZ      Germany       Luxury
8         TOYOTA        Japan  Mass Market
9     VOLKSWAGEN      Germany  Mass Market

In [48]:
c2.to_csv("Manufacturer_Data.csv")

In [50]:
#Display the shape of both datasets
print(c.shape)
print(c2.shape)

(7385, 12)
(10, 3)

In [52]:
#Display columns of both datasets
print(c.columns)
print(c2.columns)

Index(['Make', 'Model', 'Vehicle Class', 'Engine Size(L)', 'Cylinders',
       'Transmission', 'Fuel Type', 'Fuel Consumption City (L/100 km)',
       'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)',
       'Fuel Consumption Comb (mpg)', 'CO2 Emissions(g/km)'],
      dtype='object')
Index(['Make', 'Country', 'Company_Type'], dtype='object')

In [53]:
set(c.columns) & set(c2.columns)

{'Make'}

In [54]:
#Merge both datasets using inner join
merged_c=pd.merge(c,c2,on='Make',how='inner')
merged_c.head()

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km),Country,Company_Type
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196,Japan,Luxury
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221,Japan,Luxury
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136,Japan,Luxury
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255,Japan,Luxury
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244,Japan,Luxury

In [55]:
#Merge both datasets using left join
left_c=pd.merge(c,c2,on='Make',how='left')
left_c.head()

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km),Country,Company_Type
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196,Japan,Luxury
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221,Japan,Luxury
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136,Japan,Luxury
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255,Japan,Luxury
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244,Japan,Luxury

In [56]:
#Find vehicles manufactured in Germany
merged_c[merged_c['Country']=='Germany']

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km),Country,Company_Type
12,AUDI,A4,COMPACT,2.0,4,AV8,Z,9.9,7.4,8.8,32,202,Germany,Luxury
13,AUDI,A4 QUATTRO,COMPACT,2.0,4,AS8,Z,11.5,8.1,10.0,28,230,Germany,Luxury
14,AUDI,A4 QUATTRO,COMPACT,2.0,4,M6,Z,10.8,7.5,9.3,30,214,Germany,Luxury
15,AUDI,A5 CABRIOLET QUATTRO,SUBCOMPACT,2.0,4,AS8,Z,11.5,8.1,10.0,28,230,Germany,Luxury
16,AUDI,A5 QUATTRO,SUBCOMPACT,2.0,4,AS8,Z,11.5,8.1,10.0,28,230,Germany,Luxury
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3466,VOLKSWAGEN,Jetta GLI,COMPACT,2.0,4,AM7,X,9.3,7.2,8.4,34,196,Germany,Mass Market
3467,VOLKSWAGEN,Jetta GLI,COMPACT,2.0,4,M6,X,9.6,7.1,8.5,33,198,Germany,Mass Market
3468,VOLKSWAGEN,Passat,MID-SIZE,2.0,4,AS6,X,10.2,6.9,8.7,32,205,Germany,Mass Market
3469,VOLKSWAGEN,Tiguan,SUV - SMALL,2.0,4,AS8,X,10.5,8.1,9.4,30,221,Germany,Mass Market
3470,VOLKSWAGEN,Tiguan 4MOTION,SUV - SMALL,2.0,4,AS8,X,11.5,8.7,10.2,28,241,Germany,Mass Market

In [57]:
#Find luxury vehicles with CO₂ emissions greater than 300
merged_c[(merged_c['Company_Type']=='Luxury')&(merged_c['CO2 Emissions(g/km)']>300)]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km),Country,Company_Type
28,AUDI,A8L,FULL-SIZE,6.3,12,AS8,Z,18.7,11.5,15.5,18,363,Germany,Luxury
35,AUDI,Q7,SUV - STANDARD,3.0,6,AS8,Z,15.1,10.9,13.2,21,304,Germany,Luxury
37,AUDI,R8,TWO-SEATER,4.2,8,A7,Z,17.6,11.0,14.6,19,336,Germany,Luxury
38,AUDI,R8,TWO-SEATER,4.2,8,M6,Z,21.2,13.4,17.7,16,407,Germany,Luxury
39,AUDI,R8,TWO-SEATER,5.2,10,A7,Z,18.2,10.6,14.8,19,347,Germany,Luxury
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3389,MERCEDES-BENZ,AMG GT R Coupe,TWO-SEATER,4.0,8,AM7,Z,15.9,11.8,14.0,20,327,Germany,Luxury
3391,MERCEDES-BENZ,AMG S 63 4MATIC+ Cabriolet,SUBCOMPACT,4.0,8,A9,Z,15.8,9.8,13.1,22,306,Germany,Luxury
3393,MERCEDES-BENZ,AMG S 65,FULL-SIZE,6.0,12,A7,Z,18.6,10.9,15.1,19,356,Germany,Luxury
3401,MERCEDES-BENZ,G 550,SUV - STANDARD,4.0,8,A9,Z,18.0,14.1,16.3,17,378,Germany,Luxury
3403,MERCEDES-BENZ,Maybach S 650,FULL-SIZE,6.0,12,A7,Z,18.4,11.1,15.1,19,355,Germany,Luxury

In [58]:
#Find average CO₂ emissions by country
merged_c.groupby('Country')['CO2 Emissions(g/km)'].mean()

Country
Germany        254.071379
Japan          212.451299
South Korea    208.871429
USA            262.612664
Name: CO2 Emissions(g/km), dtype: float64

In [59]:
#Find the country with the highest average CO₂ emission
merged_c.groupby('Country')['CO2 Emissions(g/km)'].mean().sort_values(ascending=False).head(1)

Country
USA    262.612664
Name: CO2 Emissions(g/km), dtype: float64