<a href="https://colab.research.google.com/github/AkshayKulkarni1904/Python/blob/main/Python_Day_22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##***`Pandas`***- Data Analysis

In pandas we have 2 important data structures
- 1.Series - ID data structures(rows)
- 2.DataFrame - 2D data structure(rows,coloums)

####Q.What is the diffrence between Series and DataFrame??(Interview Question)

A **Series** is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.). It's essentially a single column of data.

A **DataFrame** is a two-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL table, or a dictionary of Series objects. It is the most commonly used pandas object.

In [1]:
import pandas as pd

data=[120,30,50,45,11]
df=pd.Series(data)
df

0    120
1     30
2     50
3     45
4     11
dtype: int64

Here, a Series `s` is created from a Python list `data`.

In [2]:
#lets creat DF
df=pd.DataFrame([[10,20,30],[30,40,50]])
df

    0   1   2
0  10  20  30
1  30  40  50

This creates a DataFrame `df` from a list of lists. Each inner list becomes a row in the DataFrame.

In [3]:
df1=pd.DataFrame([[10,20,30],[30,40,50]],columns=['A','B','C'])
df1

    A   B   C
0  10  20  30
1  30  40  50

You can also create a DataFrame and assign custom column names directly during creation, as shown above. This makes the data more readable and manageable.

In [4]:
#Converst DataFrame to array using numpy
df.to_numpy()

array([[10, 20, 30],
       [30, 40, 50]])

The `.to_numpy()` method converts a DataFrame into a NumPy array. This can be useful when you need to perform numerical operations that are optimized for NumPy arrays, or when an external library expects a NumPy array as input.

####**Assignment**

Try to creat a Series and DataFrame with str,tuple,list[list],Set,dict

Below are examples demonstrating how to create Pandas Series and DataFrames from various Python data structures like strings, tuples, lists of lists, sets, and dictionaries. This showcases the flexibility of Pandas in handling diverse data inputs.

In [5]:
#Series from String
s=pd.Series("Python")
s

0    Python
dtype: object

In [6]:
#DataFrame from String
df=pd.DataFrame(list("Python"),columns=["Letters"])
df

  Letters
0       P
1       y
2       t
3       h
4       o
5       n

In [7]:
#DataFrame from Tuple
t=(10,20,30,40)
df=pd.DataFrame(t,columns=["Numbers"])
df

   Numbers
0       10
1       20
2       30
3       40

In [8]:
#Series from List
l=[100,200,300,400]
s=pd.Series(l)
s

0    100
1    200
2    300
3    400
dtype: int64

In [9]:
#DataFrame from List
l=[100,200,300,400]
df=pd.DataFrame(l,columns=["Values"])
df

   Values
0     100
1     200
2     300
3     400

In [10]:
#Series from a List of List
l=[[1,2],[3,4],[5,6]]
s=pd.Series(l)
s

0    [1, 2]
1    [3, 4]
2    [5, 6]
dtype: object

In [11]:
#DataFrame from List of List
l=[[1,"Akshay",85],
   [2,"Harsh",90],
   [3,"Ashish",95]]
df=pd.DataFrame(l,columns=["ID","Name","Marks"])
df

   ID    Name  Marks
0   1  Akshay     85
1   2   Harsh     90
2   3  Ashish     95

In [12]:
#Series from Set
st={10,20,30,40}
s=pd.Series(list(st))
s

0    40
1    10
2    20
3    30
dtype: int64

In [13]:
#DataFrame from Set
st={10,20,30,40}
df=pd.DataFrame(list(st),columns=["Numbers"])
df

   Numbers
0       40
1       10
2       20
3       30

In [14]:
#Series from Dictionary
d={
    "Name":"Akshay",
    "Age":23,
    "City":"Pune"
}
s=pd.Series(d)
s

Name    Akshay
Age         23
City      Pune
dtype: object

In [15]:
#DataFrame from a Dictionary
d={
    "Name":["Akshay","Harsh","Ganesh"],
    "Age":[23,24,25],
    "City":["Pune","Mumbai","Delhi"]
}
df=pd.DataFrame(d)
df

     Name  Age    City
0  Akshay   23    Pune
1   Harsh   24  Mumbai
2  Ganesh   25   Delhi

###**Performing operations on raw data**

This section focuses on performing various data manipulation and analysis operations using a real-world dataset. We will load data, inspect its structure, handle missing values, and perform different types of selections and aggregations.

In [16]:
path = "https://raw.githubusercontent.com/hakimyameen/Datasets/refs/heads/main/fifa_eda.csv"

df = pd.read_csv(path)

df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

The `pd.read_csv()` function is used to load data from a CSV file into a Pandas DataFrame. The `path` variable specifies the URL of the CSV file. After loading, the entire DataFrame `df` is displayed to show its content.

In [17]:
#Display first 5 records
#by default it returns 5 values
df.head()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0

In [18]:
#slicing
df[10:21]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
10,188545,R. Lewandowski,29,Poland,90,90,FC Bayern München,77000.0,205.0,Right,4.0,4.0,ST,2014,2021-01-01,6.000000,176.0,127100.0
11,182521,T. Kroos,28,Germany,90,90,Real Madrid,76500.0,355.0,Right,4.0,3.0,LCM,2014,2022-01-01,6.000000,168.0,156800.0
12,182493,D. Godín,32,Uruguay,90,90,Atlético Madrid,44000.0,125.0,Right,3.0,2.0,CB,2010,2019-01-01,6.166667,172.0,90200.0
13,168542,David Silva,32,Spain,90,90,Manchester City,60000.0,285.0,Left,4.0,4.0,LCM,2010,2020-01-01,5.666667,148.0,111000.0
14,215914,N. Kanté,27,France,89,90,Chelsea,63000.0,225.0,Right,3.0,2.0,LDM,2016,2023-01-01,5.500000,159.0,121300.0
15,211110,P. Dybala,24,Argentina,89,94,Juventus,89000.0,205.0,Left,3.0,4.0,LF,2015,2022-01-01,5.833333,165.0,153500.0
16,202126,H. Kane,24,England,89,91,Tottenham Hotspur,83500.0,205.0,Right,3.0,3.0,ST,2010,2024-01-01,6.166667,196.0,160700.0
17,194765,A. Griezmann,27,France,89,90,Atlético Madrid,78000.0,145.0,Left,4.0,4.0,CAM,2014,2023-01-01,5.750000,161.0,165800.0
18,192448,M. ter Stegen,26,Germany,89,92,FC Barcelona,58000.0,240.0,Right,3.0,1.0,GK,2014,2022-01-01,6.166667,187.0,123300.0
19,192119,T. Courtois,26,Belgium,89,90,Real Madrid,53500.0,240.0,Left,4.0,1.0,GK,2018,2024-01-01,6.500000,212.0,113700.0
20,189511,Sergio Busquets,29,Spain,89,89,FC Barcelona,51500.0,315.0,Right,4.0,3.0,CDM,2008,2023-01-01,6.166667,168.0,105600.0

Slicing allows you to select a specific range of rows from the DataFrame. `df[start:end]` returns rows from `start` (inclusive) up to `end` (exclusive).

In [19]:
#Display last 5 records
df.tail()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [20]:
df[-3:]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [21]:
#summery
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18207 entries, 0 to 18206
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        18207 non-null  int64
 1   Name                      18207 non-null  object
 2   Age                       18207 non-null  int64
 3   Nationality               18207 non-null  object
 4   Overall                   18207 non-null  int64
 5   Potential                 18207 non-null  int64
 6   Club                      17966 non-null  object
 7   Value                     17955 non-null  float64
 8   Wage                      18207 non-null  float64
 9   Preferred Foot            18207 non-null  object
 10  International Reputation  18159 non-null  float64
 11  Skill Moves               18159 non-null  float64
 12  Position                  18207 non-null  object
 13  Joined                    18207 non-null  int64
 14  Contract Valid Until      17918 non-null  object
 15  Height                    18207 non-null  float64
 16  Weight                    18207 non-null  float64
 17  Release Clause            18207 non-null  float64
dtypes: float64(7), int64(5), object(6)
memory usage: 2.5+ MB

In [22]:
# #How to check missing values
#df.isna().sum()
# #to get missing value in percentage
(df.isna().sum() / len(df)) * 100

ID                          0.000000
Name                        0.000000
Age                         0.000000
Nationality                 0.000000
Overall                     0.000000
Potential                   0.000000
Club                        1.323667
Value                       1.384083
Wage                        0.000000
Preferred Foot              0.000000
International Reputation    0.263635
Skill Moves                 0.263635
Position                    0.000000
Joined                      0.000000
Contract Valid Until        1.587302
Height                      0.000000
Weight                      0.000000
Release Clause              0.000000
dtype: float64

If you have record of 1000 data and out of it 10/8/20 are misiing then we can `delete` if its 200 and more then we need to `handle` that

In [23]:
df.shape

(18207, 18)

In [24]:
18207 - 17907

300

In [25]:

#lets drop NaN
df.dropna().shape

(17907, 18)

In [26]:
#parmenent delet records
df.dropna(inplace=True)

The `.dropna()` method removes rows or columns containing missing values. When `inplace=True` is used, the DataFrame is modified directly, meaning the changes are permanent and not just returned as a new DataFrame. Be cautious when using `inplace=True` as it modifies the original DataFrame.

In [27]:
df.isna().sum()

ID                          0
Name                        0
Age                         0
Nationality                 0
Overall                     0
Potential                   0
Club                        0
Value                       0
Wage                        0
Preferred Foot              0
International Reputation    0
Skill Moves                 0
Position                    0
Joined                      0
Contract Valid Until        0
Height                      0
Weight                      0
Release Clause              0
dtype: int64

In [28]:
#drop column
df.columns

Index(['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club',
       'Value', 'Wage', 'Preferred Foot', 'International Reputation',
       'Skill Moves', 'Position', 'Joined', 'Contract Valid Until', 'Height',
       'Weight', 'Release Clause'],
      dtype='object')

In [29]:
#temp
df.drop(columns=['ID','Nationality',"Overall"])

,Name,Age,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,L. Messi,31,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,Cristiano Ronaldo,33,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,Neymar Jr,26,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,De Gea,27,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,K. De Bruyne,27,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,J. Lundstram,19,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,N. Christoffersson,19,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,B. Worman,16,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,D. Walker-Rice,17,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,G. Nugent,16,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [30]:
#permanent
df.drop(columns=['ID'],inplace=True)

The `.drop()` method is used to remove specified columns or rows. Using `columns=['ID']` targets the 'ID' column for removal. The `inplace=True` argument makes this change permanent in the DataFrame `df`. If `inplace=False` (default), it would return a new DataFrame with the specified column dropped, leaving the original DataFrame unchanged.

In [31]:
df.columns

Index(['Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club', 'Value',
       'Wage', 'Preferred Foot', 'International Reputation', 'Skill Moves',
       'Position', 'Joined', 'Contract Valid Until', 'Height', 'Weight',
       'Release Clause'],
      dtype='object')

In [32]:
#assignment : convert space to _
#ex.Prefered Foot --->Prefered_Foot
df.columns=df.columns.str.replace(" ","_")
df.columns

Index(['Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club', 'Value',
       'Wage', 'Preferred_Foot', 'International_Reputation', 'Skill_Moves',
       'Position', 'Joined', 'Contract_Valid_Until', 'Height', 'Weight',
       'Release_Clause'],
      dtype='object')

#**Practice questions on loaded data set**

###**Basic Operations**

In [33]:
df.head(10)

,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred_Foot,International_Reputation,Skill_Moves,Position,Joined,Contract_Valid_Until,Height,Weight,Release_Clause
0,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
5,E. Hazard,27,Belgium,91,91,Chelsea,93000.0,340.0,Right,4.0,4.0,LF,2012,2020-01-01,5.666667,163.0,172100.0
6,L. Modrić,32,Croatia,91,91,Real Madrid,67000.0,420.0,Right,4.0,4.0,RCM,2012,2020-01-01,5.666667,146.0,137400.0
7,L. Suárez,31,Uruguay,91,91,FC Barcelona,80000.0,455.0,Right,5.0,3.0,RS,2014,2021-01-01,6.000000,190.0,164000.0
8,Sergio Ramos,32,Spain,91,91,Real Madrid,51000.0,380.0,Right,4.0,3.0,RCB,2005,2020-01-01,6.000000,181.0,104600.0
9,J. Oblak,25,Slovenia,90,93,Atlético Madrid,68000.0,94.0,Right,3.0,1.0,GK,2014,2021-01-01,6.166667,192.0,144500.0

In [34]:
df.tail(10)

,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred_Foot,International_Reputation,Skill_Moves,Position,Joined,Contract_Valid_Until,Height,Weight,Release_Clause
18197,D. Holland,18,Republic of Ireland,47,61,Cork City,60.0,1.0,Right,1.0,2.0,CM,2018,2018-01-01,5.833333,141.0,88.0
18198,J. Livesey,18,England,47,70,Burton Albion,60.0,1.0,Right,1.0,1.0,GK,2018,2021-01-01,5.916667,154.0,165.0
18199,M. Baldisimo,18,Canada,47,69,Vancouver Whitecaps FC,70.0,1.0,Right,1.0,2.0,CM,2018,2021-01-01,5.500000,150.0,175.0
18200,J. Young,18,Scotland,47,62,Swindon Town,60.0,1.0,Left,1.0,2.0,ST,2015,2019-01-01,5.750000,157.0,143.0
18201,D. Walsh,18,Republic of Ireland,47,68,Waterford FC,60.0,1.0,Left,1.0,2.0,RB,2018,2018-01-01,6.083333,168.0,153.0
18202,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [35]:
#Find number of rows and columns
df.shape

(17907, 17)

In [36]:
#Display column names
df.columns

Index(['Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club', 'Value',
       'Wage', 'Preferred_Foot', 'International_Reputation', 'Skill_Moves',
       'Position', 'Joined', 'Contract_Valid_Until', 'Height', 'Weight',
       'Release_Clause'],
      dtype='object')

In [37]:
#Display data types
df.dtypes

Name                         object
Age                           int64
Nationality                  object
Overall                       int64
Potential                     int64
Club                         object
Value                       float64
Wage                        float64
Preferred_Foot               object
International_Reputation    float64
Skill_Moves                 float64
Position                     object
Joined                        int64
Contract_Valid_Until         object
Height                      float64
Weight                      float64
Release_Clause              float64
dtype: object

The `.dtypes` attribute shows the data type of each column in the DataFrame. Understanding data types is crucial for correct data manipulation and analysis.

In [38]:
#Display complete information
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17907 entries, 0 to 18206
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Name                      17907 non-null  object
 1   Age                       17907 non-null  int64
 2   Nationality               17907 non-null  object
 3   Overall                   17907 non-null  int64
 4   Potential                 17907 non-null  int64
 5   Club                      17907 non-null  object
 6   Value                     17907 non-null  float64
 7   Wage                      17907 non-null  float64
 8   Preferred_Foot            17907 non-null  object
 9   International_Reputation  17907 non-null  float64
 10  Skill_Moves               17907 non-null  float64
 11  Position                  17907 non-null  object
 12  Joined                    17907 non-null  int64
 13  Contract_Valid_Until      17907 non-null  object
 14  Height                    17907 non-null  float64
 15  Weight                    17907 non-null  float64
 16  Release_Clause            17907 non-null  float64
dtypes: float64(7), int64(4), object(6)
memory usage: 3.0+ MB

The `.info()` method provides a concise summary of a DataFrame, including the number of entries, the number of columns, a list of all columns with their non-null counts and data types, and memory usage. This is very helpful for a quick overview of the dataset's structure and completeness.

In [39]:
#Generate summary statistics
df.describe()

,Age,Overall,Potential,Value,Wage,International_Reputation,Skill_Moves,Joined,Height,Weight,Release_Clause
count,17907.000000,17907.000000,17907.000000,17907.000000,17907.000000,17907.000000,17907.000000,17907.000000,17907.000000,17907.000000,17907.000000
mean,25.095605,66.239571,71.335232,2450.132909,9.887753,1.113699,2.363042,2016.429553,5.946711,165.964316,4585.060974
std,4.660388,6.926818,6.137251,5633.206685,22.148656,0.395193,0.756256,2.027399,0.220812,15.602524,10719.096361
min,16.000000,46.000000,48.000000,10.000000,1.000000,1.000000,1.000000,1991.000000,5.083333,110.000000,13.000000
25%,21.000000,62.000000,67.000000,325.000000,1.000000,1.000000,2.000000,2016.000000,5.750000,154.000000,563.000000
50%,25.000000,66.000000,71.000000,700.000000,3.000000,1.000000,2.000000,2017.000000,5.916667,165.000000,1300.000000
75%,28.000000,71.000000,75.000000,2100.000000,9.000000,1.000000,3.000000,2018.000000,6.083333,176.000000,4585.060806
max,45.000000,94.000000,95.000000,118500.000000,565.000000,5.000000,5.000000,2018.000000,6.750000,243.000000,228100.000000

The `.describe()` method generates descriptive statistics of the DataFrame's numerical columns. This includes count, mean, standard deviation, min, max, and quartile values, providing quick insights into the data distribution.

In [40]:
#Display summary including object columns
df.describe(include="all")

,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred_Foot,International_Reputation,Skill_Moves,Position,Joined,Contract_Valid_Until,Height,Weight,Release_Clause
count,17907,17907.000000,17907,17907.000000,17907.000000,17907,17907.000000,17907.000000,17907,17907.000000,17907.000000,17907,17907.000000,17907,17907.000000,17907.000000,17907.000000
unique,16913,NaN,163,NaN,NaN,651,NaN,NaN,2,NaN,NaN,27,NaN,35,NaN,NaN,NaN
top,J. Rodríguez,NaN,England,NaN,NaN,RC Celta,NaN,NaN,Right,NaN,NaN,ST,NaN,2019-01-01,NaN,NaN,NaN
freq,11,NaN,1655,NaN,NaN,33,NaN,NaN,13748,NaN,NaN,2130,NaN,4865,NaN,NaN,NaN
mean,NaN,25.095605,NaN,66.239571,71.335232,NaN,2450.132909,9.887753,NaN,1.113699,2.363042,NaN,2016.429553,NaN,5.946711,165.964316,4585.060974
std,NaN,4.660388,NaN,6.926818,6.137251,NaN,5633.206685,22.148656,NaN,0.395193,0.756256,NaN,2.027399,NaN,0.220812,15.602524,10719.096361
min,NaN,16.000000,NaN,46.000000,48.000000,NaN,10.000000,1.000000,NaN,1.000000,1.000000,NaN,1991.000000,NaN,5.083333,110.000000,13.000000
25%,NaN,21.000000,NaN,62.000000,67.000000,NaN,325.000000,1.000000,NaN,1.000000,2.000000,NaN,2016.000000,NaN,5.750000,154.000000,563.000000
50%,NaN,25.000000,NaN,66.000000,71.000000,NaN,700.000000,3.000000,NaN,1.000000,2.000000,NaN,2017.000000,NaN,5.916667,165.000000,1300.000000
75%,NaN,28.000000,NaN,71.000000,75.000000,NaN,2100.000000,9.000000,NaN,1.000000,3.000000,NaN,2018.000000,NaN,6.083333,176.000000,4585.060806
max,NaN,45.000000,NaN,94.000000,95.000000,NaN,118500.000000,565.000000,NaN,5.000000,5.000000,NaN,2018.000000,NaN,6.750000,243.000000,228100.000000

By adding `include='all'`, the `.describe()` method also includes descriptive statistics for object (string) or categorical columns, showing unique values, top occurring value (`top`), and its frequency (`freq`), along with numerical column statistics.

###**Missing Values**

Missing values are common in real-world datasets and can significantly impact analysis. It's important to identify and handle them appropriately.

- `df.isna().sum()`: This counts the number of missing (NaN) values for each column.
- `(df.isna().sum() / len(df)) * 100`: This calculates the percentage of missing values for each column, which helps in deciding how to handle them.

In [41]:
#Count missing values
df.isna().sum()

Name                        0
Age                         0
Nationality                 0
Overall                     0
Potential                   0
Club                        0
Value                       0
Wage                        0
Preferred_Foot              0
International_Reputation    0
Skill_Moves                 0
Position                    0
Joined                      0
Contract_Valid_Until        0
Height                      0
Weight                      0
Release_Clause              0
dtype: int64

In [42]:
#Missing value percentage
(df.isna().sum()/len(df))*100

Name                        0.0
Age                         0.0
Nationality                 0.0
Overall                     0.0
Potential                   0.0
Club                        0.0
Value                       0.0
Wage                        0.0
Preferred_Foot              0.0
International_Reputation    0.0
Skill_Moves                 0.0
Position                    0.0
Joined                      0.0
Contract_Valid_Until        0.0
Height                      0.0
Weight                      0.0
Release_Clause              0.0
dtype: float64

In [43]:
#Remove rows having missing values
df.dropna()

,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred_Foot,International_Reputation,Skill_Moves,Position,Joined,Contract_Valid_Until,Height,Weight,Release_Clause
0,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [44]:
#Fill missing values
df.fillna(0)

,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred_Foot,International_Reputation,Skill_Moves,Position,Joined,Contract_Valid_Until,Height,Weight,Release_Clause
0,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

The `.fillna()` method is used to replace missing (NaN) values with a specified value. In this case, `df.fillna(0)` replaces all missing values with `0`. This is a common strategy when missing numerical data can be reasonably imputed with zero, or for demonstration purposes. However, choosing the right imputation strategy depends on the nature of the data and the problem.

###**Duplicate Data**

Duplicate data can skew analysis and lead to incorrect conclusions. Identifying and removing duplicates is an important step in data cleaning.

- `df.duplicated().sum()`: This method returns a boolean Series indicating whether each row is a duplicate of a previous row. Summing this Series gives the total number of duplicate rows.
- `df.drop_duplicates()`: This method removes duplicate rows from the DataFrame. By default, it keeps the first occurrence of a duplicate set. Similar to `dropna()`, you can use `inplace=True` to modify the DataFrame permanently.

In [45]:
#Find duplicate rows
df.duplicated().sum()

np.int64(0)

In [46]:
#Remove duplicates
df.drop_duplicates()

,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred_Foot,International_Reputation,Skill_Moves,Position,Joined,Contract_Valid_Until,Height,Weight,Release_Clause
0,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

###**Column Operations**

Column operations are essential for standardizing and improving the usability of DataFrame columns, especially for making them easier to work with in code or for database integration.

- `df.columns.str.replace(" ", "_")`: This code renames columns by replacing spaces with underscores, a common practice to make column names valid Python identifiers or to follow specific naming conventions.
- `df.columns.str.lower()` and `df.columns.str.upper()`: These convert all column names to lowercase or uppercase, respectively, which is useful for maintaining consistency.
- `df.rename(columns={"Preferred_Foot":"Foot"}, inplace=True)`: The `.rename()` method allows you to change specific column names without affecting others. `inplace=True` ensures the change is applied to the original DataFrame.

In [47]:
#Convert spaces to underscore
df.columns=df.columns.str.replace(" ","_")

In [50]:
#Convert column names to lowercase
df.columns=df.columns.str.lower()
df.head(3)

,name,age,nationality,overall,potential,club,value,wage,preferred_foot,international_reputation,skill_moves,position,joined,contract_valid_until,height,weight,release_clause
0,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0

In [51]:
#Convert column names to uppercase
df.columns=df.columns.str.upper()
df.head(3)

,NAME,AGE,NATIONALITY,OVERALL,POTENTIAL,CLUB,VALUE,WAGE,PREFERRED_FOOT,INTERNATIONAL_REPUTATION,SKILL_MOVES,POSITION,JOINED,CONTRACT_VALID_UNTIL,HEIGHT,WEIGHT,RELEASE_CLAUSE
0,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0

In [57]:
#Rename a column
df.rename(columns={"Preferred_Foot":"Foot"}, inplace=True)
df.head(2)

,NAME,AGE,NATIONALITY,OVERALL,POTENTIAL,CLUB,VALUE,WAGE,PREFERRED_FOOT,INTERNATIONAL_REPUTATION,SKILL_MOVES,POSITION,JOINED,CONTRACT_VALID_UNTIL,HEIGHT,WEIGHT,RELEASE_CLAUSE
0,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0

###**Selection**

Selecting data is a fundamental operation in Pandas. You can select single columns, multiple columns, or specific rows using various methods.

- `df["COLUMN_NAME"]`: Selects a single column, returning a Series.
- `df[["COLUMN_NAME1", "COLUMN_NAME2"]]`: Selects multiple columns, returning a DataFrame.
- `.iloc[index]`: Selects rows by their integer-location based indexing (positional indexing).
- `.iloc[start:end]`: Selects a range of rows by integer-location.

In [63]:
#Display Name column
df["NAME"]

0                  L. Messi
1         Cristiano Ronaldo
2                 Neymar Jr
3                    De Gea
4              K. De Bruyne
                ...
18202          J. Lundstram
18203    N. Christoffersson
18204             B. Worman
18205        D. Walker-Rice
18206             G. Nugent
Name: NAME, Length: 17907, dtype: object

In [64]:
#Display Name and Age
df[["NAME","AGE"]]

                     NAME  AGE
0                L. Messi   31
1       Cristiano Ronaldo   33
2               Neymar Jr   26
3                  De Gea   27
4            K. De Bruyne   27
...                   ...  ...
18202        J. Lundstram   19
18203  N. Christoffersson   19
18204           B. Worman   16
18205      D. Walker-Rice   17
18206           G. Nugent   16

[17907 rows x 2 columns]

In [66]:
#First player
df.iloc[0]

NAME                            L. Messi
AGE                                   31
NATIONALITY                    Argentina
OVERALL                               94
POTENTIAL                             94
CLUB                        FC Barcelona
VALUE                           110500.0
WAGE                               565.0
PREFERRED_FOOT                      Left
INTERNATIONAL_REPUTATION             5.0
SKILL_MOVES                          4.0
POSITION                              RF
JOINED                              2004
CONTRACT_VALID_UNTIL          2021-01-01
HEIGHT                          5.583333
WEIGHT                             159.0
RELEASE_CLAUSE                  226500.0
Name: 0, dtype: object

In [68]:
#First five rows
df.iloc[:5]

,NAME,AGE,NATIONALITY,OVERALL,POTENTIAL,CLUB,VALUE,WAGE,PREFERRED_FOOT,INTERNATIONAL_REPUTATION,SKILL_MOVES,POSITION,JOINED,CONTRACT_VALID_UNTIL,HEIGHT,WEIGHT,RELEASE_CLAUSE
0,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0

###**Filtering**

Filtering allows you to select rows based on one or more conditions, enabling you to focus on specific subsets of your data. This is a powerful feature for data exploration and analysis.

- **Single Condition**: `df[df["COLUMN"] > value]` selects rows where the specified column meets a single criterion.
- **Multiple Conditions (AND)**: `df[(condition1) & (condition2)]` combines conditions using the `&` operator, requiring all conditions to be true.
- **Multiple Conditions (OR)**: `df[(condition1) | (condition2)]` combines conditions using the `|` operator, requiring at least one condition to be true.
- **`between()` Method**: `df["COLUMN"].between(lower_bound, upper_bound)` selects rows where a numerical column falls within a specified range.
- **`isin()` Method**: `df["COLUMN"].isin(['value1', 'value2'])` selects rows where a column's value is present in a given list of values.

In [70]:
#Players older than 30
df[df["AGE"]>30]

,NAME,AGE,NATIONALITY,OVERALL,POTENTIAL,CLUB,VALUE,WAGE,PREFERRED_FOOT,INTERNATIONAL_REPUTATION,SKILL_MOVES,POSITION,JOINED,CONTRACT_VALID_UNTIL,HEIGHT,WEIGHT,RELEASE_CLAUSE
0,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
6,L. Modrić,32,Croatia,91,91,Real Madrid,67000.0,420.0,Right,4.0,4.0,RCM,2012,2020-01-01,5.666667,146.0,137400.0
7,L. Suárez,31,Uruguay,91,91,FC Barcelona,80000.0,455.0,Right,5.0,3.0,RS,2014,2021-01-01,6.000000,190.0,164000.0
8,Sergio Ramos,32,Spain,91,91,Real Madrid,51000.0,380.0,Right,4.0,3.0,RCB,2005,2020-01-01,6.000000,181.0,104600.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17704,F. Nicastro,36,Italy,53,53,Neuchâtel Xamax,10.0,1.0,Right,1.0,1.0,GK,2017,2021-01-01,6.000000,172.0,15.0
17842,Zhou Ting,39,China PR,52,52,Dalian YiFang FC,10.0,1.0,Right,1.0,2.0,CM,2017,2020-01-01,6.083333,163.0,22.0
17866,N. Hatta,32,Japan,52,52,Júbilo Iwata,30.0,1.0,Right,1.0,1.0,GK,2005,2021-01-01,6.083333,168.0,38.0
18043,A. Suzuki,31,Japan,50,50,Yokohama F. Marinos,20.0,1.0,Right,1.0,1.0,GK,2017,2021-01-01,6.000000,176.0,25.0
18171,Y. Uchimura,33,Japan,48,48,Hokkaido Consadole Sapporo,20.0,1.0,Right,1.0,2.0,CAM,2010,2021-01-01,5.750000,148.0,25.0

In [71]:
#Overall rating above 90
df[df["OVERALL"]>90]

,NAME,AGE,NATIONALITY,OVERALL,POTENTIAL,CLUB,VALUE,WAGE,PREFERRED_FOOT,INTERNATIONAL_REPUTATION,SKILL_MOVES,POSITION,JOINED,CONTRACT_VALID_UNTIL,HEIGHT,WEIGHT,RELEASE_CLAUSE
0,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
5,E. Hazard,27,Belgium,91,91,Chelsea,93000.0,340.0,Right,4.0,4.0,LF,2012,2020-01-01,5.666667,163.0,172100.0
6,L. Modrić,32,Croatia,91,91,Real Madrid,67000.0,420.0,Right,4.0,4.0,RCM,2012,2020-01-01,5.666667,146.0,137400.0
7,L. Suárez,31,Uruguay,91,91,FC Barcelona,80000.0,455.0,Right,5.0,3.0,RS,2014,2021-01-01,6.000000,190.0,164000.0
8,Sergio Ramos,32,Spain,91,91,Real Madrid,51000.0,380.0,Right,4.0,3.0,RCB,2005,2020-01-01,6.000000,181.0,104600.0

In [74]:
#Left-footed players
df[df["PREFERRED_FOOT"]=='Left']

,NAME,AGE,NATIONALITY,OVERALL,POTENTIAL,CLUB,VALUE,WAGE,PREFERRED_FOOT,INTERNATIONAL_REPUTATION,SKILL_MOVES,POSITION,JOINED,CONTRACT_VALID_UNTIL,HEIGHT,WEIGHT,RELEASE_CLAUSE
0,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
13,David Silva,32,Spain,90,90,Manchester City,60000.0,285.0,Left,4.0,4.0,LCM,2010,2020-01-01,5.666667,148.0,111000.0
15,P. Dybala,24,Argentina,89,94,Juventus,89000.0,205.0,Left,3.0,4.0,LF,2015,2022-01-01,5.833333,165.0,153500.0
17,A. Griezmann,27,France,89,90,Atlético Madrid,78000.0,145.0,Left,4.0,4.0,CAM,2014,2023-01-01,5.750000,161.0,165800.0
19,T. Courtois,26,Belgium,89,90,Real Madrid,53500.0,240.0,Left,4.0,1.0,GK,2018,2024-01-01,6.500000,212.0,113700.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18172,C. Hawkins,18,England,48,65,Burton Albion,50.0,1.0,Left,1.0,1.0,GK,2018,2019-01-01,6.166667,165.0,119.0
18175,E. Clarke,19,England,48,59,Fleetwood Town,40.0,1.0,Left,1.0,2.0,LB,2018,2019-01-01,5.666667,154.0,78.0
18191,J. Norville-Williams,18,England,47,65,Cambridge United,50.0,1.0,Left,1.0,2.0,LB,2018,2021-01-01,5.916667,168.0,119.0
18200,J. Young,18,Scotland,47,62,Swindon Town,60.0,1.0,Left,1.0,2.0,ST,2015,2019-01-01,5.750000,157.0,143.0
18201,D. Walsh,18,Republic of Ireland,47,68,Waterford FC,60.0,1.0,Left,1.0,2.0,RB,2018,2018-01-01,6.083333,168.0,153.0

In [75]:
#Right-footed players
df[df["PREFERRED_FOOT"]=="Right"]

,NAME,AGE,NATIONALITY,OVERALL,POTENTIAL,CLUB,VALUE,WAGE,PREFERRED_FOOT,INTERNATIONAL_REPUTATION,SKILL_MOVES,POSITION,JOINED,CONTRACT_VALID_UNTIL,HEIGHT,WEIGHT,RELEASE_CLAUSE
1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
5,E. Hazard,27,Belgium,91,91,Chelsea,93000.0,340.0,Right,4.0,4.0,LF,2012,2020-01-01,5.666667,163.0,172100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [76]:
#Players aged between 20 and 25
df[df["AGE"].between(20,25)]

,NAME,AGE,NATIONALITY,OVERALL,POTENTIAL,CLUB,VALUE,WAGE,PREFERRED_FOOT,INTERNATIONAL_REPUTATION,SKILL_MOVES,POSITION,JOINED,CONTRACT_VALID_UNTIL,HEIGHT,WEIGHT,RELEASE_CLAUSE
9,J. Oblak,25,Slovenia,90,93,Atlético Madrid,68000.0,94.0,Right,3.0,1.0,GK,2014,2021-01-01,6.166667,192.0,144500.0
15,P. Dybala,24,Argentina,89,94,Juventus,89000.0,205.0,Left,3.0,4.0,LF,2015,2022-01-01,5.833333,165.0,153500.0
16,H. Kane,24,England,89,91,Tottenham Hotspur,83500.0,205.0,Right,3.0,3.0,ST,2010,2024-01-01,6.166667,196.0,160700.0
42,S. Umtiti,24,France,87,92,FC Barcelona,57000.0,205.0,Left,3.0,2.0,CB,2016,2023-01-01,6.000000,165.0,121100.0
43,M. Icardi,25,Argentina,87,90,Inter,64500.0,130.0,Right,3.0,3.0,ST,2013,2021-01-01,5.916667,165.0,114500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18163,Wang Xin,20,China PR,48,58,Guangzhou R&F; FC,40.0,1.0,Right,1.0,2.0,RWB,2018,2022-01-01,6.000000,154.0,94.0
18167,Wu Lei,21,China PR,48,58,Tianjin Quanjian FC,40.0,2.0,Right,1.0,2.0,LDM,2018,2022-01-01,6.000000,159.0,94.0
18173,R. Takae,20,Japan,48,63,Gamba Osaka,60.0,1.0,Right,1.0,2.0,CDM,2016,2021-01-01,5.583333,132.0,113.0
18180,M. Hurst,22,Scotland,48,58,St. Johnstone FC,40.0,1.0,Right,1.0,1.0,GK,2013,2019-01-01,6.083333,172.0,78.0
18186,Zhang Yufeng,20,China PR,47,64,Beijing Renhe FC,60.0,1.0,Right,1.0,2.0,CM,2016,2019-01-01,5.833333,174.0,167.0

In [77]:
#Barcelona players
df[df["CLUB"]=="FC Barcelona"]

,NAME,AGE,NATIONALITY,OVERALL,POTENTIAL,CLUB,VALUE,WAGE,PREFERRED_FOOT,INTERNATIONAL_REPUTATION,SKILL_MOVES,POSITION,JOINED,CONTRACT_VALID_UNTIL,HEIGHT,WEIGHT,RELEASE_CLAUSE
0,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
7,L. Suárez,31,Uruguay,91,91,FC Barcelona,80000.0,455.0,Right,5.0,3.0,RS,2014,2021-01-01,6.000000,190.0,164000.0
18,M. ter Stegen,26,Germany,89,92,FC Barcelona,58000.0,240.0,Right,3.0,1.0,GK,2014,2022-01-01,6.166667,187.0,123300.0
20,Sergio Busquets,29,Spain,89,89,FC Barcelona,51500.0,315.0,Right,4.0,3.0,CDM,2008,2023-01-01,6.166667,168.0,105600.0
32,Coutinho,26,Brazil,88,89,FC Barcelona,69500.0,340.0,Right,3.0,5.0,LW,2018,2023-01-01,5.666667,150.0,147700.0
42,S. Umtiti,24,France,87,92,FC Barcelona,57000.0,205.0,Left,3.0,2.0,CB,2016,2023-01-01,6.000000,165.0,121100.0
49,Jordi Alba,29,Spain,87,87,FC Barcelona,38000.0,250.0,Left,3.0,3.0,LB,2012,2020-01-01,5.583333,150.0,77900.0
53,I. Rakitić,30,Croatia,87,87,FC Barcelona,46500.0,260.0,Right,4.0,3.0,RCM,2014,2021-01-01,6.000000,172.0,95300.0
54,Piqué,31,Spain,87,87,FC Barcelona,34000.0,240.0,Right,4.0,2.0,RCB,2008,2022-01-01,6.333333,187.0,69700.0
96,A. Vidal,31,Chile,85,85,FC Barcelona,26000.0,205.0,Right,4.0,3.0,CAM,2018,2021-01-01,5.916667,165.0,53300.0
155,O. Dembélé,21,France,83,92,FC Barcelona,40000.0,155.0,Left,3.0,4.0,RW,2017,2022-01-01,5.833333,148.0,90000.0
192,Sergi Roberto,26,Spain,83,86,FC Barcelona,26500.0,170.0,Right,3.0,4.0,RB,2013,2022-01-01,5.833333,150.0,56300.0
228,Arthur,21,Brazil,82,90,FC Barcelona,32500.0,125.0,Right,1.0,4.0,LCM,2018,2024-01-01,5.583333,161.0,73100.0
236,Malcom,21,Brazil,82,89,FC Barcelona,31500.0,140.0,Left,2.0,4.0,RW,2018,2023-01-01,5.666667,163.0,70900.0
239,C. Lenglet,23,France,82,88,FC Barcelona,26000.0,135.0,Left,1.0,2.0,LCB,2018,2023-01-01,6.083333,179.0,58500.0
263,Rafinha,25,Brazil,82,87,FC Barcelona,29500.0,165.0,Left,2.0,4.0,CAM,2013,2020-01-01,5.750000,157.0,62700.0
266,J. Cillessen,29,Netherlands,82,84,FC Barcelona,18000.0,135.0,Right,3.0,1.0,GK,2016,2021-01-01,6.083333,183.0,38300.0
324,Nélson Semedo,24,Portugal,81,86,FC Barcelona,20000.0,125.0,Right,2.0,4.0,RB,2017,2022-01-01,5.833333,148.0,42500.0
613,Denis Suárez,24,Spain,79,86,FC Barcelona,17500.0,120.0,Right,2.0,3.0,CM,2016,2020-01-01,5.750000,152.0,39400.0
1007,Munir,22,Spain,77,83,FC Barcelona,12500.0,115.0,Left,2.0,4.0,ST,2015,2019-01-01,5.750000,152.0,28100.0
1037,T. Vermaelen,32,Belgium,77,77,FC Barcelona,5000.0,110.0,Left,3.0,2.0,CB,2014,2019-01-01,6.000000,176.0,10300.0
3118,Sergi Samper,23,Spain,73,80,FC Barcelona,4800.0,69.0,Right,1.0,3.0,CDM,2016,2020-01-01,6.000000,161.0,10800.0
3684,Aleñá,20,Spain,72,85,FC Barcelona,6000.0,58.0,Left,1.0,3.0,CM,2018,2022-01-01,5.916667,161.0,16100.0
6000,M. Wagué,19,Senegal,69,81,FC Barcelona,1600.0,20.0,Right,1.0,3.0,RB,2018,2023-01-01,5.833333,154.0,3600.0
6102,Riqui Puig,18,Spain,69,89,FC Barcelona,2100.0,24.0,Right,1.0,3.0,CM,2018,2021-01-01,5.583333,123.0,6500.0
8284,Oriol Busquets,19,Spain,67,82,FC Barcelona,1500.0,14.0,Right,1.0,3.0,CDM,2017,2021-01-01,6.083333,170.0,4000.0
8289,Abel Ruiz,18,Spain,67,83,FC Barcelona,1600.0,21.0,Right,1.0,3.0,ST,2017,2021-01-01,6.000000,161.0,4200.0
8857,Miranda,18,Spain,66,81,FC Barcelona,1200.0,12.0,Left,1.0,2.0,LB,2018,2021-01-01,6.083333,168.0,3200.0
10526,Chumi,19,Spain,65,82,FC Barcelona,1000.0,11.0,Right,1.0,2.0,CB,2014,2020-01-01,6.083333,172.0,2800.0
10777,Jorge Cuenca,18,Spain,65,78,FC Barcelona,850.0,11.0,Left,1.0,2.0,CB,2017,2019-01-01,6.166667,168.0,2300.0
11300,Guillem Jaime,19,Spain,64,80,FC Barcelona,975.0,13.0,Right,1.0,3.0,RW,2018,2020-01-01,5.833333,154.0,2600.0
12502,Ezkieta,21,Spain,63,75,FC Barcelona,525.0,10.0,Right,1.0,1.0,GK,2015,2019-01-01,6.333333,172.0,1200.0
14286,Iñaki Peña,19,Spain,61,78,FC Barcelona,450.0,4.0,Right,1.0,1.0,GK,2018,2021-01-01,6.000000,172.0,1200.0

In [79]:
#Age >30 and Overall >85
df[(df["AGE"]>30)&(df["OVERALL"]>85)]

,NAME,AGE,NATIONALITY,OVERALL,POTENTIAL,CLUB,VALUE,WAGE,PREFERRED_FOOT,INTERNATIONAL_REPUTATION,SKILL_MOVES,POSITION,JOINED,CONTRACT_VALID_UNTIL,HEIGHT,WEIGHT,RELEASE_CLAUSE
0,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
6,L. Modrić,32,Croatia,91,91,Real Madrid,67000.0,420.0,Right,4.0,4.0,RCM,2012,2020-01-01,5.666667,146.0,137400.0
7,L. Suárez,31,Uruguay,91,91,FC Barcelona,80000.0,455.0,Right,5.0,3.0,RS,2014,2021-01-01,6.000000,190.0,164000.0
8,Sergio Ramos,32,Spain,91,91,Real Madrid,51000.0,380.0,Right,4.0,3.0,RCB,2005,2020-01-01,6.000000,181.0,104600.0
12,D. Godín,32,Uruguay,90,90,Atlético Madrid,44000.0,125.0,Right,3.0,2.0,CB,2010,2019-01-01,6.166667,172.0,90200.0
13,David Silva,32,Spain,90,90,Manchester City,60000.0,285.0,Left,4.0,4.0,LCM,2010,2020-01-01,5.666667,148.0,111000.0
21,E. Cavani,31,Uruguay,89,89,Paris Saint-Germain,60000.0,200.0,Right,4.0,3.0,LS,2013,2020-01-01,6.083333,170.0,111000.0
22,M. Neuer,32,Germany,89,89,FC Bayern München,38000.0,130.0,Right,5.0,1.0,GK,2011,2021-01-01,6.333333,203.0,62700.0
24,G. Chiellini,33,Italy,89,89,Juventus,27000.0,215.0,Left,4.0,2.0,LCB,2005,2020-01-01,6.166667,187.0,44600.0
37,H. Lloris,31,France,88,88,Tottenham Hotspur,36000.0,150.0,Left,4.0,1.0,GK,2012,2022-01-01,6.166667,181.0,66600.0
39,Thiago Silva,33,Brazil,88,88,Paris Saint-Germain,24000.0,165.0,Right,4.0,2.0,RCB,2012,2020-01-01,6.000000,181.0,44400.0
40,S. Handanovič,33,Slovenia,88,88,Inter,30000.0,110.0,Right,3.0,1.0,GK,2012,2021-01-01,6.333333,203.0,51000.0
41,G. Buffon,40,Italy,88,88,Paris Saint-Germain,4000.0,77.0,Right,4.0,1.0,GK,2018,2019-01-01,6.333333,203.0,7400.0
46,K. Navas,31,Costa Rica,87,87,Real Madrid,30500.0,195.0,Right,3.0,1.0,GK,2014,2020-01-01,6.083333,176.0,62500.0
50,D. Mertens,31,Belgium,87,87,Napoli,45000.0,135.0,Right,3.0,4.0,RF,2013,2020-01-01,5.583333,134.0,76500.0
51,J. Vertonghen,31,Belgium,87,87,Tottenham Hotspur,34000.0,155.0,Left,3.0,3.0,LCB,2012,2019-01-01,6.166667,190.0,62900.0
54,Piqué,31,Spain,87,87,FC Barcelona,34000.0,240.0,Right,4.0,2.0,RCB,2008,2022-01-01,6.333333,187.0,69700.0
70,L. Bonucci,31,Italy,86,86,Juventus,30000.0,160.0,Right,3.0,2.0,RCB,2018,2023-01-01,6.250000,187.0,49500.0
73,M. Benatia,31,Morocco,86,86,Juventus,30000.0,160.0,Right,3.0,2.0,CB,2014,2020-01-01,6.166667,207.0,49500.0
75,Fernandinho,33,Brazil,86,86,Manchester City,18000.0,185.0,Right,3.0,3.0,CDM,2013,2020-01-01,5.833333,148.0,33300.0
76,Iniesta,34,Spain,86,86,Vissel Kobe,21500.0,21.0,Right,4.0,4.0,LF,2018,2021-01-01,5.583333,150.0,26900.0

In [80]:
#Brazil or Argentina players
df[df['NATIONALITY'].isin(['Brazil','Argentina'])]

,NAME,AGE,NATIONALITY,OVERALL,POTENTIAL,CLUB,VALUE,WAGE,PREFERRED_FOOT,INTERNATIONAL_REPUTATION,SKILL_MOVES,POSITION,JOINED,CONTRACT_VALID_UNTIL,HEIGHT,WEIGHT,RELEASE_CLAUSE
0,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
15,P. Dybala,24,Argentina,89,94,Juventus,89000.0,205.0,Left,3.0,4.0,LF,2015,2022-01-01,5.833333,165.0,153500.0
23,S. Agüero,30,Argentina,89,89,Manchester City,64500.0,300.0,Right,4.0,4.0,ST,2011,2021-01-01,5.666667,154.0,119300.0
27,Casemiro,26,Brazil,88,90,Real Madrid,59500.0,285.0,Right,3.0,2.0,CDM,2013,2021-01-01,6.083333,185.0,126400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17611,Felipe Ferreyra,20,Brazil,53,67,Curicó Unido,130.0,1.0,Right,1.0,2.0,ST,2016,2022-01-01,5.750000,159.0,257.0
17638,E. Alarcón,25,Argentina,53,57,Patronato,50.0,2.0,Right,1.0,1.0,GK,2016,2019-01-01,6.000000,165.0,76.0
17861,F. Bustamante,19,Argentina,52,66,Club Atlético Tigre,110.0,1.0,Right,1.0,2.0,RM,2018,2021-01-01,5.500000,143.0,234.0
17987,L. Finochietto,21,Argentina,51,59,Argentinos Juniors,40.0,1.0,Right,1.0,1.0,GK,2017,2021-01-01,6.083333,170.0,66.0
18170,Nicolas Firmino,17,Brazil,48,70,New England Revolution,60.0,1.0,Right,1.0,2.0,CAM,2018,2021-01-01,5.916667,154.0,147.0

###**Sorting**

Sorting your DataFrame helps in organizing data and making patterns or extremes easier to observe.

- `df.sort_values("COLUMN")`: Sorts the DataFrame by the values in a specified column in ascending order by default.
- `df.sort_values("COLUMN", ascending=False)`: Sorts in descending order.
- `df.sort_values(["COLUMN1", "COLUMN2"])`: Sorts by multiple columns, applying the second sort key to rows that have equal values in the first sort key.

In [81]:
#Sort by Age
df.sort_values("AGE")

,NAME,AGE,NATIONALITY,OVERALL,POTENTIAL,CLUB,VALUE,WAGE,PREFERRED_FOOT,INTERNATIONAL_REPUTATION,SKILL_MOVES,POSITION,JOINED,CONTRACT_VALID_UNTIL,HEIGHT,WEIGHT,RELEASE_CLAUSE
18206,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0
18162,T. Gundelund,16,Denmark,48,66,Vejle Boldklub,50.0,1.0,Right,1.0,2.0,RWB,2018,2020-01-01,5.916667,154.0,94.0
17115,C. Bassett,16,United States,55,77,Colorado Rapids,180.0,1.0,Right,1.0,2.0,CDM,2018,2019-01-01,5.916667,148.0,441.0
17841,F. Tauchhammer,16,Austria,52,71,Wolfsberger AC,90.0,1.0,Right,1.0,2.0,RB,2018,2021-01-01,6.000000,141.0,187.0
17776,M. Köstenbauer,16,Austria,52,74,FC Admira Wacker Mödling,90.0,1.0,Right,1.0,1.0,GK,2018,2021-01-01,6.083333,154.0,221.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4187,C. Lucchetti,40,Argentina,71,71,Atlético Tucumán,160.0,4.0,Right,1.0,1.0,GK,2012,2019-01-01,6.000000,152.0,240.0
7225,C. Muñoz,41,Argentina,68,68,CD Universidad de Concepción,60.0,1.0,Right,1.0,1.0,GK,2013,2018-01-01,5.833333,161.0,84.0
15426,M. Tyler,41,England,59,59,Peterborough United,10.0,1.0,Right,1.0,1.0,GK,2016,2019-01-01,6.000000,183.0,18.0
10545,S. Narazaki,42,Japan,65,65,Nagoya Grampus,40.0,1.0,Right,2.0,1.0,GK,1999,2021-01-01,6.166667,176.0,50.0
4741,O. Pérez,45,Mexico,71,71,Pachuca,160.0,8.0,Right,2.0,1.0,GK,1991,2021-01-01,5.666667,165.0,272.0

In [82]:
#Sort by Overall descending
df.sort_values("OVERALL",ascending=False)

,NAME,AGE,NATIONALITY,OVERALL,POTENTIAL,CLUB,VALUE,WAGE,PREFERRED_FOOT,INTERNATIONAL_REPUTATION,SKILL_MOVES,POSITION,JOINED,CONTRACT_VALID_UNTIL,HEIGHT,WEIGHT,RELEASE_CLAUSE
0,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
7,L. Suárez,31,Uruguay,91,91,FC Barcelona,80000.0,455.0,Right,5.0,3.0,RS,2014,2021-01-01,6.000000,190.0,164000.0
8,Sergio Ramos,32,Spain,91,91,Real Madrid,51000.0,380.0,Right,4.0,3.0,RCB,2005,2020-01-01,6.000000,181.0,104600.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18204,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18187,C. Ehlich,19,Germany,47,59,SpVgg Unterhaching,40.0,1.0,Right,1.0,2.0,RB,2017,2020-01-01,5.833333,161.0,66.0
18205,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18188,L. Collins,17,Wales,47,62,Newport County,60.0,1.0,Right,1.0,2.0,CM,2017,2021-01-01,5.833333,148.0,143.0
18206,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [83]:
#Sort by Age and Overall
df.sort_values(["AGE","OVERALL"])

,NAME,AGE,NATIONALITY,OVERALL,POTENTIAL,CLUB,VALUE,WAGE,PREFERRED_FOOT,INTERNATIONAL_REPUTATION,SKILL_MOVES,POSITION,JOINED,CONTRACT_VALID_UNTIL,HEIGHT,WEIGHT,RELEASE_CLAUSE
18206,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0
18204,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18162,T. Gundelund,16,Denmark,48,66,Vejle Boldklub,50.0,1.0,Right,1.0,2.0,RWB,2018,2020-01-01,5.916667,154.0,94.0
18166,N. Ayéva,16,Sweden,48,72,Örebro SK,70.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,5.833333,154.0,158.0
18124,G. Hollywood,16,Republic of Ireland,49,67,Bray Wanderers,60.0,1.0,Right,1.0,2.0,CM,2017,2018-01-01,5.833333,146.0,131.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41,G. Buffon,40,Italy,88,88,Paris Saint-Germain,4000.0,77.0,Right,4.0,1.0,GK,2018,2019-01-01,6.333333,203.0,7400.0
15426,M. Tyler,41,England,59,59,Peterborough United,10.0,1.0,Right,1.0,1.0,GK,2016,2019-01-01,6.000000,183.0,18.0
7225,C. Muñoz,41,Argentina,68,68,CD Universidad de Concepción,60.0,1.0,Right,1.0,1.0,GK,2013,2018-01-01,5.833333,161.0,84.0
10545,S. Narazaki,42,Japan,65,65,Nagoya Grampus,40.0,1.0,Right,2.0,1.0,GK,1999,2021-01-01,6.166667,176.0,50.0
4741,O. Pérez,45,Mexico,71,71,Pachuca,160.0,8.0,Right,2.0,1.0,GK,1991,2021-01-01,5.666667,165.0,272.0

###**Unique Values**

Understanding the unique values and their frequencies within a column is vital for categorical data analysis and can reveal insights into data distribution.

- `df["COLUMN"].unique()`: Returns an array of all the unique values in the specified column.
- `df['COLUMN'].nunique()`: Returns the number of unique values in the column.
- `df['COLUMN'].value_counts()`: Returns a Series containing counts of unique values. The Series will be in descending order so that the first element is the most frequently-occurring element.

In [84]:
#Unique nationalities
df["NATIONALITY"].unique()

array(['Argentina', 'Portugal', 'Brazil', 'Spain', 'Belgium', 'Croatia',
       'Uruguay', 'Slovenia', 'Poland', 'Germany', 'France', 'England',
       'Italy', 'Egypt', 'Colombia', 'Denmark', 'Gabon', 'Wales',
       'Senegal', 'Costa Rica', 'Slovakia', 'Netherlands',
       'Bosnia Herzegovina', 'Morocco', 'Serbia', 'Algeria', 'Austria',
       'Greece', 'Chile', 'Sweden', 'Korea Republic', 'Finland', 'Guinea',
       'Montenegro', 'Armenia', 'Switzerland', 'Norway', 'Czech Republic',
       'Scotland', 'Ghana', 'Central African Rep.', 'DR Congo',
       'Ivory Coast', 'Russia', 'Ukraine', 'Iceland', 'Mexico', 'Jamaica',
       'Albania', 'Venezuela', 'Japan', 'Turkey', 'Ecuador', 'Paraguay',
       'Mali', 'Nigeria', 'Cameroon', 'Dominican Republic', 'Israel',
       'Kenya', 'Hungary', 'Republic of Ireland', 'Romania',
       'United States', 'Cape Verde', 'Australia', 'Peru', 'Togo',
       'Syria', 'Zimbabwe', 'Angola', 'Burkina Faso', 'Iran', 'Estonia',
       'Tunisia', 'Equatorial Guinea', 'New Zealand', 'FYR Macedonia',
       'United Arab Emirates', 'China PR', 'Guinea Bissau', 'Bulgaria',
       'Kosovo', 'South Africa', 'Madagascar', 'Georgia', 'Tanzania',
       'Gambia', 'Cuba', 'Belarus', 'Uzbekistan', 'Benin', 'Congo',
       'Mozambique', 'Honduras', 'Canada', 'Northern Ireland', 'Cyprus',
       'Saudi Arabia', 'Curacao', 'Moldova', 'Bolivia',
       'Trinidad & Tobago', 'Sierra Leone', 'Zambia', 'Chad',
       'Philippines', 'Haiti', 'Comoros', 'Libya', 'Panama',
       'São Tomé & Príncipe', 'Eritrea', 'Oman', 'Iraq', 'Burundi',
       'Fiji', 'New Caledonia', 'Lithuania', 'Luxembourg', 'Korea DPR',
       'Liechtenstein', 'St Kitts Nevis', 'Latvia', 'Suriname', 'Uganda',
       'El Salvador', 'Bermuda', 'Kuwait', 'Antigua & Barbuda',
       'Thailand', 'Mauritius', 'Guatemala', 'Liberia', 'Kazakhstan',
       'Niger', 'Mauritania', 'Montserrat', 'Namibia', 'Azerbaijan',
       'Guam', 'Faroe Islands', 'Nicaragua', 'Barbados', 'Lebanon',
       'Palestine', 'Guyana', 'Sudan', 'St Lucia', 'Ethiopia',
       'Puerto Rico', 'Grenada', 'Jordan', 'Rwanda', 'Qatar',
       'Afghanistan', 'Hong Kong', 'Andorra', 'Malta', 'Belize',
       'South Sudan', 'Indonesia', 'Botswana'], dtype=object)

In [85]:
#Number of Nationalities
df['NATIONALITY'].nunique()

163

In [86]:
#Count players from each nationality
df['NATIONALITY'].value_counts()

NATIONALITY
England        1655
Germany        1195
Spain          1071
Argentina       935
France          910
               ...
Malta             1
Belize            1
South Sudan       1
Indonesia         1
Botswana          1
Name: count, Length: 163, dtype: int64

###**Statistics**

Pandas provides a wide range of statistical functions to summarize your data, helping you to quickly understand central tendencies and spread.

- `df['COLUMN'].mean()`: Calculates the average of values in the column.
- `df['COLUMN'].min()`: Finds the minimum value in the column.
- `df['COLUMN'].max()`: Finds the maximum value in the column.
- These methods can be applied to numerical columns to get quick summary statistics.

In [87]:
#Average age
df['AGE'].mean()

np.float64(25.095605070642765)

In [88]:
#Youngest player
df['AGE'].min()

16

In [90]:
#Oldest player
df['AGE'].max()

45

In [92]:
#Highest overall rating
df["OVERALL"].max()

94

###**GroupBy**

The `groupby()` method is used to split the DataFrame into groups based on some criteria. Once grouped, you can apply an aggregation function (like `mean()`, `sum()`, `count()`) to each group. This is a powerful tool for analyzing relationships and patterns across different categories.

- `df.groupby("GROUPING_COLUMN")["TARGET_COLUMN"].mean()`: Groups the DataFrame by `GROUPING_COLUMN` and then calculates the mean of `TARGET_COLUMN` for each group.
- This can be extended to `count()`, `sum()`, `max()`, `min()`, etc., to get different aggregated statistics for each group.

In [93]:
#Average age by nationality
df.groupby("NATIONALITY")["AGE"].mean()

NATIONALITY
Afghanistan    22.500000
Albania        24.076923
Algeria        27.050000
Andorra        28.000000
Angola         25.866667
                 ...
Uzbekistan     29.500000
Venezuela      24.305085
Wales          24.789062
Zambia         22.222222
Zimbabwe       26.846154
Name: AGE, Length: 163, dtype: float64

In [94]:
#Average overall by position
df.groupby("POSITION")["OVERALL"].mean()

POSITION
CAM    66.867865
CB     64.993718
CDM    66.313034
CF     65.824324
CM     63.697168
GK     64.583208
LAM    71.857143
LB     65.848926
LCB    69.218898
LCM    69.334190
LDM    69.100418
LF     73.866667
LM     66.675875
LS     70.077670
LW     66.639037
LWB    66.512821
RAM    72.285714
RB     66.032334
RCB    69.315951
RCM    69.105943
RDM    69.739837
RF     73.250000
RM     66.473070
RS     69.537313
RW     66.835616
RWB    64.655172
ST     65.512676
Name: OVERALL, dtype: float64

In [97]:
#Number of players in each club
df.groupby("CLUB")["NAME"].count()

CLUB
 SSV Jahn Regensburg     29
1. FC Heidenheim 1846    28
1. FC Kaiserslautern     26
1. FC Köln               28
1. FC Magdeburg          26
                         ..
Zagłębie Sosnowiec       25
Çaykur Rizespor          30
Örebro SK                27
Östersunds FK            22
Śląsk Wrocław            24
Name: NAME, Length: 651, dtype: int64

In [98]:
#Average potential by preferred foot
df.groupby("PREFERRED_FOOT")["POTENTIAL"].mean()

PREFERRED_FOOT
Left     71.761962
Right    71.206139
Name: POTENTIAL, dtype: float64

####**Top Players**

Identifying top or bottom performers or values in a dataset is a common analytical task. Pandas provides convenient methods for this.

- `df.nlargest(n, "COLUMN")`: Returns the `n` rows with the largest values in the specified column.
- `df.nsmallest(n, "COLUMN")`: Returns the `n` rows with the smallest values in the specified column.
- `df.loc[df["COLUMN"].idxmax()]`: Returns the entire row corresponding to the maximum value in the specified column.
- `df.loc[df["COLUMN"].idxmin()]`: Returns the entire row corresponding to the minimum value in the specified column.

In [99]:
#Top 10 players by Overall
df.nlargest(10,"OVERALL")

,NAME,AGE,NATIONALITY,OVERALL,POTENTIAL,CLUB,VALUE,WAGE,PREFERRED_FOOT,INTERNATIONAL_REPUTATION,SKILL_MOVES,POSITION,JOINED,CONTRACT_VALID_UNTIL,HEIGHT,WEIGHT,RELEASE_CLAUSE
0,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
5,E. Hazard,27,Belgium,91,91,Chelsea,93000.0,340.0,Right,4.0,4.0,LF,2012,2020-01-01,5.666667,163.0,172100.0
6,L. Modrić,32,Croatia,91,91,Real Madrid,67000.0,420.0,Right,4.0,4.0,RCM,2012,2020-01-01,5.666667,146.0,137400.0
7,L. Suárez,31,Uruguay,91,91,FC Barcelona,80000.0,455.0,Right,5.0,3.0,RS,2014,2021-01-01,6.000000,190.0,164000.0
8,Sergio Ramos,32,Spain,91,91,Real Madrid,51000.0,380.0,Right,4.0,3.0,RCB,2005,2020-01-01,6.000000,181.0,104600.0
9,J. Oblak,25,Slovenia,90,93,Atlético Madrid,68000.0,94.0,Right,3.0,1.0,GK,2014,2021-01-01,6.166667,192.0,144500.0

In [100]:
#Top 5 youngest players
df.nsmallest(5,"AGE")

,NAME,AGE,NATIONALITY,OVERALL,POTENTIAL,CLUB,VALUE,WAGE,PREFERRED_FOOT,INTERNATIONAL_REPUTATION,SKILL_MOVES,POSITION,JOINED,CONTRACT_VALID_UNTIL,HEIGHT,WEIGHT,RELEASE_CLAUSE
11457,W. Geubbels,16,France,64,86,AS Monaco,1000.0,5.0,Right,1.0,3.0,ST,2018,2023-01-01,6.083333,159.0,2900.0
11732,A. Taoui,16,France,64,75,Toulouse Football Club,700.0,3.0,Left,1.0,3.0,ST,2018,2021-01-01,5.833333,152.0,1500.0
12496,Pelayo Morilla,16,Spain,63,81,Real Sporting de Gijón,725.0,1.0,Left,1.0,3.0,RM,2018,2022-01-01,6.000000,154.0,1600.0
12828,Guerrero,16,Spain,63,76,CF Rayo Majadahonda,625.0,1.0,Left,1.0,3.0,CM,2018,2019-01-01,5.916667,165.0,1400.0
13293,H. Massengo,16,France,62,75,AS Monaco,450.0,2.0,Right,1.0,2.0,CDM,2018,2021-01-01,5.833333,146.0,1100.0

In [101]:
#Player with highest Overall
df.loc[df["OVERALL"].idxmax()]

NAME                            L. Messi
AGE                                   31
NATIONALITY                    Argentina
OVERALL                               94
POTENTIAL                             94
CLUB                        FC Barcelona
VALUE                           110500.0
WAGE                               565.0
PREFERRED_FOOT                      Left
INTERNATIONAL_REPUTATION             5.0
SKILL_MOVES                          4.0
POSITION                              RF
JOINED                              2004
CONTRACT_VALID_UNTIL          2021-01-01
HEIGHT                          5.583333
WEIGHT                             159.0
RELEASE_CLAUSE                  226500.0
Name: 0, dtype: object

In [102]:
#Player with highest Potential
df.loc[df["POTENTIAL"].idxmax()]

NAME                                  K. Mbappé
AGE                                          19
NATIONALITY                              France
OVERALL                                      88
POTENTIAL                                    95
CLUB                        Paris Saint-Germain
VALUE                                   81000.0
WAGE                                      100.0
PREFERRED_FOOT                            Right
INTERNATIONAL_REPUTATION                    3.0
SKILL_MOVES                                 5.0
POSITION                                     RM
JOINED                                     2018
CONTRACT_VALID_UNTIL                 2022-01-01
HEIGHT                                 5.833333
WEIGHT                                    161.0
RELEASE_CLAUSE                         166100.0
Name: 25, dtype: object

###**Value Counts**

Value counts provide a quick way to understand the distribution of categorical data, showing the frequency of each unique value in a Series.

- `df['COLUMN'].value_counts()`: This method returns a Series containing counts of unique values in the specified column. The result is sorted in descending order by default, so the most frequent element appears first. This is particularly useful for understanding the composition of categorical features.

In [104]:
#Preferred foot count
df['PREFERRED_FOOT'].value_counts()

PREFERRED_FOOT
Right    13748
Left      4159
Name: count, dtype: int64

In [105]:
#Position count
df['POSITION'].value_counts()

POSITION
ST     2130
GK     1989
CB     1751
CM     1377
LB     1304
RB     1268
RM     1114
LM     1086
CAM     946
CDM     936
RCB     652
LCB     635
LCM     389
RCM     387
LW      374
RW      365
RDM     246
LDM     239
LS      206
RS      201
RWB      87
LWB      78
CF       74
LAM      21
RAM      21
RF       16
LF       15
Name: count, dtype: int64