<a href="https://colab.research.google.com/github/AkshayKulkarni1904/Python/blob/main/notebooks/day_23_pandas_II.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Pandas part-II**

In [1]:
import pandas as pd
path = "https://raw.githubusercontent.com/hakimyameen/Datasets/refs/heads/main/fifa_eda.csv"

df = pd.read_csv(path)

df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [2]:
#access single column
df['Nationality']

0        Argentina
1         Portugal
2           Brazil
3            Spain
4          Belgium
           ...
18202      England
18203       Sweden
18204      England
18205      England
18206      England
Name: Nationality, Length: 18207, dtype: object

In [3]:
#approach 2 using dot.operator
df.Age

0        31
1        33
2        26
3        27
4        27
         ..
18202    19
18203    19
18204    16
18205    17
18206    16
Name: Age, Length: 18207, dtype: int64

In [4]:
#access more than one columns [[]]
#to access limited rows use .hear(n)
df[['Age','Club']].head()

   Age                 Club
0   31         FC Barcelona
1   33             Juventus
2   26  Paris Saint-Germain
3   27    Manchester United
4   27      Manchester City

In [5]:
#to access row and columns we have 2 more options in pandas
#loc--lable based selection
#stop is inclusive in loc
df.loc[:3,'Name':'Overall'] #[row,column]

                Name  Age Nationality  Overall
0           L. Messi   31   Argentina       94
1  Cristiano Ronaldo   33    Portugal       94
2          Neymar Jr   26      Brazil       92
3             De Gea   27       Spain       91

In [6]:
df.loc[:2,['Name','Club','Nationality','Age']]

                Name                 Club Nationality  Age
0           L. Messi         FC Barcelona   Argentina   31
1  Cristiano Ronaldo             Juventus    Portugal   33
2          Neymar Jr  Paris Saint-Germain      Brazil   26

###Interview question

####Diffrence between iloc and loc?

*`iloc`* is index based where stop is exclusive and *`loc`* is lable based where stop is inclusive

- *`iloc` (integer location)*: Selects data by row and column positions (integer indices). It does not accept labels or boolean arrays and uses exclusive slicing for ranges.
- *`loc` (label location)*: Selects data by row and column labels. It can accept labels, boolean arrays, or slices, and uses inclusive slicing for ranges.

In [7]:
#iloc --> index based selection
#stop is exclusive
df.iloc[:2,:]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0

In [8]:
df.iloc[:2,[1,3,10,5]]

                Name Nationality  International Reputation  Potential
0           L. Messi   Argentina                       5.0         94
1  Cristiano Ronaldo    Portugal                       5.0         94

In [9]:
#Creat a copy befor making parmanent changes
new_df=df.copy()

In [10]:
#delete
new_df.drop(columns=['Club','ID'])

,Name,Age,Nationality,Overall,Potential,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,L. Messi,31,Argentina,94,94,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,Cristiano Ronaldo,33,Portugal,94,94,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,Neymar Jr,26,Brazil,92,93,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,De Gea,27,Spain,91,93,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,K. De Bruyne,27,Belgium,91,92,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,J. Lundstram,19,England,47,65,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,N. Christoffersson,19,Sweden,47,63,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,B. Worman,16,England,47,67,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,D. Walker-Rice,17,England,47,66,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,G. Nugent,16,England,46,66,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [11]:
#check duplicate records
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
18202    False
18203    False
18204    False
18205    False
18206    False
Length: 18207, dtype: bool

In [12]:
#sum of duplicate if present
df.duplicated().sum()

np.int64(0)

In [13]:
#To delete duplicate we use drop_duplicate
#as no duplicate present in this data no result
df.drop_duplicates(inplace=True)
df.head()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0

In [14]:
#add new column to data
df['New_name']='Ak'
df.head()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause,New_name
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0,Ak
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0,Ak
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0,Ak
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0,Ak
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0,Ak

###**Assignment**

1. How to add a row in df
2. How to append two dataframe
3. How to concatanate two or more dataframe
4. How to perform merge operation
5. How to perform join operation

In [15]:
#How to add a row in df
new_player = pd.DataFrame({
    "ID":[99998],
    "Name":["Rahul"],
    "Age":[21],
    "Nationality":["India"],
    "Overall":[72],
    "Potential":[80],
    "Club":[" FC"],
    "Value":["80000"],
    "Wage":["3000"],
    "Preferred Foot":["Left"],
    "International Reputation":[1],
    "Skill Moves":[2],
    "Position":["CM"],
    "Joined":["2024"],
    "Contract Valid Until":["2028-01-01"],
    "Height":["175 cm"],
    "Weight":["70 kg"],
    "Release Clause":["1000000"]
})

df = pd.concat([df, new_player], ignore_index=True)

df.tail()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause,New_name
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.25,170.0,113.0,Ak
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0,Ak
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0,Ak
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0,Ak
18207,99998,Rahul,21,India,72,80,FC,80000,3000,Left,1.0,2.0,CM,2024,2028-01-01,175 cm,70 kg,1000000,NaN

In [16]:
#Append Two DataFrames
#Concatenate Two or More DataFrames
df2= df.tail(5)
df2

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause,New_name
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.25,170.0,113.0,Ak
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0,Ak
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0,Ak
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0,Ak
18207,99998,Rahul,21,India,72,80,FC,80000,3000,Left,1.0,2.0,CM,2024,2028-01-01,175 cm,70 kg,1000000,NaN

In [17]:
new_df=pd.concat([df,df2],ignore_index=True)
new_df.tail()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause,New_name
18208,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.25,170.0,113.0,Ak
18209,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0,Ak
18210,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0,Ak
18211,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0,Ak
18212,99998,Rahul,21,India,72,80,FC,80000,3000,Left,1.0,2.0,CM,2024,2028-01-01,175 cm,70 kg,1000000,NaN

In [18]:
#Vertical Concatenation (Rows)
result=pd.concat([df,df2])
result.tail()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause,New_name
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.25,170.0,113.0,Ak
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0,Ak
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0,Ak
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0,Ak
18207,99998,Rahul,21,India,72,80,FC,80000,3000,Left,1.0,2.0,CM,2024,2028-01-01,175 cm,70 kg,1000000,NaN

In [19]:
#Horizontal Concatenation (Columns)
leaft = df[["Name",'Age']].head()
right = df[["Overall","Club"]].head()
result=pd.concat([leaft,right],axis=1)
result

                Name  Age  Overall                 Club
0           L. Messi   31       94         FC Barcelona
1  Cristiano Ronaldo   33       94             Juventus
2          Neymar Jr   26       92  Paris Saint-Germain
3             De Gea   27       91    Manchester United
4       K. De Bruyne   27       91      Manchester City

In [21]:
#Concatenate Three DataFrames
df1 = df.head(2)
df2 = df.iloc[2:4]
df3 = df.tail(2)
df_concat = pd.concat([df1, df2, df3], ignore_index=True)
df_concat

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause,New_name
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0,Ak
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0,Ak
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.75,150.0,228100.0,Ak
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0,Ak
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0,Ak
18207,99998,Rahul,21,India,72,80,FC,80000,3000,Left,1.0,2.0,CM,2024,2028-01-01,175 cm,70 kg,1000000,NaN

In [23]:
club = pd.DataFrame({
    "Club":["Juventus","Real Madrid","FC Barcelona"],
    "Country":["Italy","Spain","Spain"]
})

club

           Club Country
0      Juventus   Italy
1   Real Madrid   Spain
2  FC Barcelona   Spain

In [24]:
#Merge using the common column Club
merged = pd.merge(df,club,on='Club')
merged.head()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause,New_name,Country
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0,Ak,Spain
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0,Ak,Italy
2,177003,L. Modrić,32,Croatia,91,91,Real Madrid,67000.0,420.0,Right,4.0,4.0,RCM,2012,2020-01-01,5.666667,146.0,137400.0,Ak,Spain
3,176580,L. Suárez,31,Uruguay,91,91,FC Barcelona,80000.0,455.0,Right,5.0,3.0,RS,2014,2021-01-01,6.0,190.0,164000.0,Ak,Spain
4,155862,Sergio Ramos,32,Spain,91,91,Real Madrid,51000.0,380.0,Right,4.0,3.0,RCB,2005,2020-01-01,6.0,181.0,104600.0,Ak,Spain

In [27]:
#Left Merge
pd.merge(df,club,on='Club',how='left')

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause,New_name,Country
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0,Ak,Spain
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0,Ak,Italy
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.75,150.0,228100.0,Ak,NaN
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0,Ak,NaN
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0,Ak,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.25,170.0,113.0,Ak,NaN
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0,Ak,NaN
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0,Ak,NaN
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0,Ak,NaN
18207,99998,Rahul,21,India,72,80,FC,80000,3000,Left,1.0,2.0,CM,2024,2028-01-01,175 cm,70 kg,1000000,NaN,NaN

#

In [26]:
#Right Merge
pd.merge(df,club,on='Club',how='right')

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause,New_name,Country
0,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0,Ak,Italy
1,211110,P. Dybala,24,Argentina,89,94,Juventus,89000.0,205.0,Left,3.0,4.0,LF,2015,2022-01-01,5.833333,165.0,153500.0,Ak,Italy
2,138956,G. Chiellini,33,Italy,89,89,Juventus,27000.0,215.0,Left,4.0,2.0,LCB,2005,2020-01-01,6.166667,187.0,44600.0,Ak,Italy
3,191043,Alex Sandro,27,Brazil,86,86,Juventus,36500.0,160.0,Left,3.0,3.0,LB,2015,2020-01-01,5.916667,176.0,60200.0,Ak,Italy
4,190483,Douglas Costa,27,Brazil,86,86,Juventus,46500.0,175.0,Left,3.0,5.0,LM,2018,2022-01-01,5.666667,154.0,76700.0,Ak,Italy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,241810,Chumi,19,Spain,65,82,FC Barcelona,1000.0,11.0,Right,1.0,2.0,CB,2014,2020-01-01,6.083333,172.0,2800.0,Ak,Spain
87,237522,Jorge Cuenca,18,Spain,65,78,FC Barcelona,850.0,11.0,Left,1.0,2.0,CB,2017,2019-01-01,6.166667,168.0,2300.0,Ak,Spain
88,246599,Guillem Jaime,19,Spain,64,80,FC Barcelona,975.0,13.0,Right,1.0,3.0,RW,2018,2020-01-01,5.833333,154.0,2600.0,Ak,Spain
89,225395,Ezkieta,21,Spain,63,75,FC Barcelona,525.0,10.0,Right,1.0,1.0,GK,2015,2019-01-01,6.333333,172.0,1200.0,Ak,Spain
90,246139,Iñaki Peña,19,Spain,61,78,FC Barcelona,450.0,4.0,Right,1.0,1.0,GK,2018,2021-01-01,6.0,172.0,1200.0,Ak,Spain

In [25]:
#Outer Merge
pd.merge(df,club,on='Club',how='outer')

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause,New_name,Country
0,99998,Rahul,21,India,72,80,FC,80000,3000,Left,1.0,2.0,CM,2024,2028-01-01,175 cm,70 kg,1000000,NaN,NaN
1,211920,M. Grüttner,32,Germany,71,71,SSV Jahn Regensburg,1900.0,9.0,Right,1.0,2.0,RS,2016,2020-01-01,6.083333,185.0,2900.0,Ak,NaN
2,156437,P. Pentke,33,Germany,70,70,SSV Jahn Regensburg,900.0,5.0,Right,1.0,1.0,GK,2015,2019-01-01,6.25,187.0,1400.0,Ak,NaN
3,193679,M. Correia,29,Portugal,70,70,SSV Jahn Regensburg,1400.0,7.0,Right,1.0,2.0,LCB,2018,2020-01-01,6.083333,179.0,2100.0,Ak,NaN
4,218534,S. Adamyan,25,Armenia,70,73,SSV Jahn Regensburg,2300.0,7.0,Right,1.0,3.0,LS,2017,2021-01-01,6.0,170.0,3700.0,Ak,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18203,245164,V. Kaith,21,India,55,64,NaN,NaN,0.0,Right,1.0,1.0,GK,2016,NaN,6.166667,176.0,4585.060806,Ak,NaN
18204,243131,K. Taimi,26,Finland,55,57,NaN,NaN,0.0,Right,1.0,2.0,RB,2016,NaN,6.333333,187.0,4585.060806,Ak,NaN
18205,233526,S. Passi,23,India,54,63,NaN,NaN,0.0,Right,1.0,2.0,RM,2016,NaN,5.75,143.0,4585.060806,Ak,NaN
18206,236452,D. Lalhlimpuia,20,India,54,67,NaN,NaN,0.0,Right,1.0,2.0,GK,2016,NaN,6.0,168.0,4585.060806,Ak,NaN
18207,234508,C. Singh,21,India,53,62,NaN,NaN,0.0,Right,1.0,2.0,LB,2016,NaN,6.25,174.0,4585.060806,Ak,NaN

In [30]:
#Join Operation
#Create two small DataFrames.
country = pd.DataFrame({
    "Country":["India","Italy","Spain","Germany"],
    "Capital":["New Delhi","Rome","Madrid","Berlin"]
})
country.index = [0,1,2,3]
country

   Country    Capital
0    India  New Delhi
1    Italy       Rome
2    Spain     Madrid
3  Germany     Berlin

In [31]:
left = df[["Name","Nationality"]].head(3)

right = pd.DataFrame({
    "Nationality":["Portugal","Argentina","Brazil"],
    "Continent":["Europe","South America","South America"]
}).set_index("Nationality")

left

                Name Nationality
0           L. Messi   Argentina
1  Cristiano Ronaldo    Portugal
2          Neymar Jr      Brazil

In [32]:
#Set index and join.
joined = left.set_index("Nationality").join(right)
joined

                          Name      Continent
Nationality
Argentina             L. Messi  South America
Portugal     Cristiano Ronaldo         Europe
Brazil               Neymar Jr  South America